export const defaultParams = {
  studentCount: 1000,
  hscGpaMean: 4.5,
  hscGpaStdDev: 0.3,
  attendanceMean: 80,
  attendanceStdDev: 15,
  semesters: 9,
  initialCredits: 12,
  maxCredits: 22,
  minCredits: 9,
  semestersMean: 9,
  semestersStdDev: 1.5,
  attendanceImpact: 0.4,
  hscGpaImpact: 0.45,
  maxCreditImpact: 0.05,
  subjectCount: 60,
  passingGrade: 2.0,
  maxGrade: 4.0,
};
